# Generated by Django 4.2.6 on 2023-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='migrant',
            field=models.BooleanField(),
        ),
    ]
