# Generated by Django 4.2.6 on 2023-10-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_alter_character_migrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='sexuals_orientations',
            field=models.CharField(max_length=50),
        ),
    ]
