# Generated by Django 4.2.6 on 2023-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_remove_character_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='motto',
            field=models.CharField(max_length=200),
        ),
    ]
