# Generated by Django 4.2.6 on 2023-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_remove_character_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(max_length=100),
        ),
    ]
