# Generated by Django 4.2.6 on 2023-10-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_alter_character_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
