# Generated by Django 4.2.7 on 2023-11-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_alter_character_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
