# Generated by Django 4.2.7 on 2023-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_formquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='panswers',
            field=models.CharField(default='', max_length=100),
        ),
    ]
