# Generated by Django 4.2.7 on 2023-11-10 13:19

import Form.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_formquestion_panswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='panswers',
            field=Form.models.SeparatedValuesField(verbose_name=''),
        ),
    ]
