# Generated by Django 4.2.7 on 2023-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_alter_formquestion_panswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexuality', models.CharField(choices=[('Gay', 'Gay'), ('Bisexual', 'Bisexual'), ('Lesbiana', 'Lesbiana'), ('Asexual', 'Asexual'), ('Arromantico', 'Arromantico'), ('Pansexual', 'Pansexual'), ('Sin etiqueta', 'Sin etiqueta'), ('Otra', 'Otra')], max_length=50)),
                ('neurodivergence', models.CharField(choices=[['Trastorno limite de personalidad', 'Trastorno limite de personalidad'], ['Autismo', 'Autismo'], ['TDAH', 'TDAH'], ['Dislexia', 'Dislexia'], ['Sindrome de Tourette', 'Sindrome de Tourette'], ['Otra', 'Otra']], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='panswers',
        ),
    ]
