# Generated by Django 4.2.7 on 2023-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0013_fq_remove_formquestion_panswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fq',
            name='sexuality',
            field=models.CharField(choices=[('Gay', 'Gay'), ('Bisexual', 'Bisexual'), ('Lesbiana', 'Lesbiana'), ('Asexual', 'Asexual'), ('Arromantico', 'Arromantico'), ('Pansexual', 'Pansexual'), ('Sin etiqueta', 'Sin etiqueta'), ('Otra', 'Otra')], max_length=50, verbose_name='Sexualidad'),
        ),
    ]
